# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
# This is stupid, but it's how GH works I guess.
name: "check dist/"

on:
  push:
    branches:
      - trunk
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    uses: "KyoriPowered/.github/.github/workflows/shared-action-check-dist.yaml@trunk"
    secrets: "inherit"
