name: "test"

on: "push"

jobs:
  test:
    uses: "KyoriPowered/.github/.github/workflows/shared-action-test.yaml@trunk"
    secrets: "inherit"

  functional-test:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4.2.2"
    - name: "Test API calls"
      uses: ./
      id: test-run
      with:
        debug: true
        output_file: './test-out.txt'
    - name: "Validate output"
      env:
        LATEST: "${{ steps.test-run.outputs.latest_rc_or_nightly }}"
        RELEASE: "${{ steps.test-run.outputs.release }}"
        RC: "${{ steps.test-run.outputs.rc }}"
        NIGHTLY: "${{ steps.test-run.outputs.nightly }}"
        RELEASE_NIGHTLY: "${{ steps.test-run.outputs.release_nightly }}"
      run: |
        echo "::notice:: Latest: $LATEST"
        echo "::notice:: Release: $RELEASE"
        echo "::notice:: RC: $RC"
        echo "::notice:: Nightly: $NIGHTLY"
        echo "::notice:: Release Nightly: $RELEASE_NIGHTLY"

        touch test-out.txt # just in case

        echo "## Release info file" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat test-out.txt >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
